workflows:
  capacitor-app:
    name: Build React + Vite + Capacitor (Android + iOS)
    max_build_duration: 90
    environment:
      node: latest
      java: 21
      xcode: latest
      cocoapods: default
      groups:
        - keystore_credentials     # Android signing
        - appstore_credentials     # iOS signing
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Run tests
        script: |
          npm test || echo "No tests found, skipping..."

      - name: Build Vite app
        script: |
          npm run build

      # --- Android build ---
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease

      # --- iOS build ---
      - name: Sync Capacitor iOS
        script: |
          cd $CM_BUILD_DIR
          npx cap sync ios
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            clean archive
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_output/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - ios_output/*.ipa
    publishing:
      email:
        recipients:
          - tokoloho57@gmail.com
